spring.application.name=Teachers_AI

#server
server.port=9999

#jsp 
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/WEB-INF/views/

gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=gemini-3.5-flash-lite

spring.datasource.url=jdbc:postgresql://localhost:5432/pyprojectTeachersfrnd
spring.datasource.username=postgres
spring.datasource.password=root

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true